## RESTHeart simple security configuration file.

## look at undertow documentation for information about predictates syntax 
## http://undertow.io/documentation/core/predicates-attributes-handlers.html

## the special role $unauthenticated allows to give permissions without requiring authentication
---
users:
    - userid: user1
      password: user1
      roles: [powerusers]
          
    - userid: user2
      password: user2
      roles: [users]
    
    - userid: admin
      password: admin
      roles: [users, admins]
      
permissions:
    - role: admins
      predicate: path-prefix[path="/"]
      
    - role: $unauthenticated
      predicate: path-prefix[path="/mydb/refcoll1"] and method[value="GET"]
      
    - role: powerusers
      predicate: path-prefix[path="/mydb"] and method[value="GET"]
      
    - role: powerusers
      predicate: path-prefix[path="/mytmpdb"]
      
    - role: users
      predicate: path-prefix[path="/mydb/refcoll2"] and method[value="GET"]
    
    - role: users
      predicate: path[path="/mydb/refcoll2"] and method[value="GET"]